### ISSUE TITLE
Can't go to next page

### ISSUE THREAD

**Issue by paulx3** [Wangqinxiao/MyIonicProject#1]
![image](https://user-images.githubusercontent.com/6678782/28107208-5beaba22-6719-11e7-8936-22b7ead0bca3.png)
![image](https://user-images.githubusercontent.com/6678782/28107218-621c6a76-6719-11e7-816a-f3d0c728a56b.png)

**Comment by Wangqinxiao** [comment]
don't worry baby, I will fix it
